package types

import "errors"

var (
	ErrUserNotFound           = errors.New("user not found")
	ErrSessionNotFound        = errors.New("session not found")
	ErrDriverIDNotExist       = errors.New("driver ID is not exist")
	ErrDriverRegistered       = errors.New("driver already registered")
	ErrDriverAlreadyOnline    = errors.New("driver already online")
	ErrDriverAlreadyOffline   = errors.New("driver already offline")
	ErrDriverAlreadyOnRide    = errors.New("driver is already on a ride")
	ErrDriverAlreadyBusy      = errors.New("driver already busy")
	ErrDriverMustBeAvailable  = errors.New("driver must be available")
	ErrDriverMustBeEnRoute    = errors.New("driver must be en route")
	ErrDriverMustBeBusy       = errors.New("driver must be busy")
	ErrLicenseAlreadyExists   = errors.New("license already exist")
	ErrInvalidLicenseFormat   = errors.New("invalid license format: AA123123")
	ErrNoCoordinates          = errors.New("no coordinates found")
	ErrDriverLocationNotFound = errors.New("driver location not found")
	ErrRideNotFound           = errors.New("ride not found")
	ErrRideNotArrived         = errors.New("ride status is not 'arrived'")
	ErrRideDriverMismatch     = errors.New("ride does not belong to the driver")
	ErrRideCannotBeCancelled  = errors.New("ride cannot be cancelled")
	ErrRideNotInProgress      = errors.New("ride is not in progress")
	ErrInvalidRideStatus      = errors.New("invalid ride status")
	ErrNotFound               = errors.New("requested item not found")
	ErrDriverSearchTimeout    = errors.New("driver search time exceeded")
	ErrDriversNotFound        = errors.New("drivers are not found")
	ErrRideStatusNotMatched   = errors.New("ride status must be matched")
	ErrListenTimeout          = errors.New("listen timeout")
	ErrPassengerHasActiveRide = errors.New("passenger already has an active ride")

	ErrDatabaseFailed            = errors.New("database failed")
	ErrFailedToPublishRideStatus = errors.New("failed to publish ride status")
)
