#!/bin/bash
# This script generates Swagger documentation and updates the import paths

# Generate swagger docs for all services
echo "Generating Swagger documentation for all services..."
make swagger-all

# Create import file for generated docs
cat > internal/adapter/http/server/swagger_imports.go << 'EOF'
// Code generated by swagger setup script. DO NOT EDIT.
// This file contains conditional imports for swagger documentation.

package server

import (
	_ "github.com/Temutjin2k/ride-hail-system/docs/admin"  // Admin service swagger docs
	_ "github.com/Temutjin2k/ride-hail-system/docs/auth"   // Auth service swagger docs  
	_ "github.com/Temutjin2k/ride-hail-system/docs/driver" // Driver service swagger docs
	_ "github.com/Temutjin2k/ride-hail-system/docs/ride"   // Ride service swagger docs
)
EOF

echo ""
echo "✅ Swagger documentation generated successfully!"
echo ""
echo "Each service now has unique descriptions:"
echo "  • Ride Service   - localhost:3000/swagger/"
echo "  • Driver Service - localhost:3001/swagger/"
echo "  • Admin Service  - localhost:3004/swagger/"
echo "  • Auth Service   - localhost:3005/swagger/"
